Improve transformation

diff --git a/.github/workflows/transform-files b/.github/workflows/transform-files
--- a/.github/workflows/transform-files
+++ b/.github/workflows/transform-files
@@ -1,9 +1,20 @@
 #!/bin/bash
+set -e  # Abort on error
+
 mkdir -p docs
+
 for xml_file in data/gold/*.xml; do
     base_name=$(basename "$xml_file" .xml)
-    docker run --rm -i -u $(id -u) --volume "${PWD}:/src" klakegg/saxon:he xslt \
-    -s:$xml_file \
-    -xsl:xslt/dataset-to-html.xslt \
-    -o:docs/$base_name.html
+    
+    echo "Processing $xml_file..."
+    docker run --rm -i -u $(id -u) --volume "${PWD}:/src" --platform=linux/amd64/v8 klakegg/saxon:he xslt \
+        -s:$xml_file \
+        -xsl:xslt/dataset-to-html.xslt \
+        -o:docs/$base_name.html \
+        $1
+
+    if [ $? -ne 0 ]; then
+        echo "Error: Saxon failed for $xml_file. Aborting script."
+        exit 1
+    fi
 done
